humanoid:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  l_hip_yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_hip_yaw
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  l_hip_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_hip_roll
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  l_hip_pitch_front_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_hip_pitch_front
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  l_hip_pitch_back_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_hip_pitch_back
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  l_knee_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_knee
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  l_ank_pitch_front_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_ank_pitch_front
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  l_ank_pitch_back_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_ank_pitch_back
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  l_ank_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_ank
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  l_ank_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_ank_roll
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
#------------------------------------------------------
  r_hip_yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_hip_yaw
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  r_hip_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_hip_roll
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  r_hip_pitch_front_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_hip_pitch_front
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  r_hip_pitch_back_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_hip_pitch_back
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  r_knee_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_knee
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  r_ank_pitch_front_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_ank_pitch_front
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  r_ank_pitch_back_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_ank_pitch_back
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  r_ank_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_ank
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  r_ank_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_ank_roll
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
#-----------------------------------------------------------
  l_sho_pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_sho_pitch
    pid: {p: 1000.0, i: 100, d: 100}  # 5 1 0
  l_sho_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_sho_roll
    pid: {p: 1000.0, i: 100, d: 100}  # 5 1 0
  l_el_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_el
    pid: {p: 1000.0, i: 100, d: 100}  # 5 1 0
  l_el_yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_el_yaw
    pid: {p: 1000.0, i: 100, d: 100}  # 5 1 0
#------------------------------------------------------
  r_sho_pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_sho_pitch
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  r_sho_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_sho_roll
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  r_el_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_el
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  r_el_yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_el_yaw
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
#----------------------------------------------------------
  head_pan_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_pan
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0
  head_tilt_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_tilt
    pid: {p: 50.0, i: 0, d: 0}  # 5 1 0



