humanoid:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  Lshoulder_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Lshoulder_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}  # 5 1 0
  Larm_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Larm_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}  # 5 1 0
  Lelbow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Lelbow_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}  # 5 1 0
  Lhand_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Lhand_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}  # 5 1 0
  Rhip_yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rhip_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}  # 5 1 0
  Lhip_yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Lhip_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Rhip_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rhip_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Lhip_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Lhip_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Rpaha_belakang_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rpaha_belakang_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Lpaha_belakang_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Lpaha_belakang_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Rlutut_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rlutut_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Llutut_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Llutut_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Rpaha_depan_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rpaha_depan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Lpaha_depan_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Lpaha_depan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Rbetis_depan_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rbetis_depan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Lbetis_depan_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Lbetis_depan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Rbetis_belakang_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rbetis_belakang_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Lbetis_belakang_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Lbetis_belakang_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Lankle_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Lankle_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Rankle_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rankle_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Ltelapak_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Ltelapak_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Rtelapak_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rtelapak_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}